magazin/app/urls.py
from django.urls import path, include

from app.views import StartPage, AddProduct, ProductList, UpdateProduct

app_name = 'administrator'

urlpatterns = [
    path('', StartPage.as_view(), name="start"),
    path('administrator/add/', AddProduct.as_view(), name='add'),
    path('administrator/products/', ProductList.as_view(), name='products'),
    path('administrator/products/<slug:slug_param>/update', UpdateProduct.as_view(), name='update')

]

magazin/magazin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('users/', include('user.urls'))
]

magazin/user/urls.py
from django.urls import path, include


from user.views import ProductList, StartPage, ProductDetail

app_name = 'users'

urlpatterns = [
    path('start/', StartPage.as_view(), name='start'),
    path('products/', ProductList.as_view(), name='products'),
    path('products/<slug:slug_param>/', ProductDetail.as_view(), name='detail')

]

magazin/app/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Magazin(models.Model):
    title = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=100)
    price = models.PositiveIntegerField()
    status = models.BooleanField()
    date_of_purchase = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.title} - {self.price}'

    def get_absolute_url(self):
        return reverse("users:detail", args=(self.slug, ))

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

magazin/user/models.py
from django.db import models

# Create your models here.

magazin/app/forms.py
from django import forms

from app.models import Magazin


class ProductModelForm(forms.ModelForm):
    class Meta:
        model = Magazin
        fields = ['title', 'category', 'price', 'status']

magazin/app/views.py
from django.forms import modelform_factory
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView, UpdateView

from app.forms import ProductModelForm
from app.models import Magazin


class StartPage(TemplateView):
    template_name = 'app/index.html'


class AddProduct(CreateView):
    model = Magazin
    form_class = modelform_factory(Magazin, fields=['title', 'category', 'price', 'status'])
    template_name = 'app/add.html'
    success_url = reverse_lazy('administrator:start')


class ProductList(ListView):
    model = Magazin
    template_name = 'app/products.html'
    context_object_name = 'products'


class UpdateProduct(UpdateView):
    model = Magazin
    form_class = ProductModelForm
    template_name = 'app/update.html'
    slug_field = 'slug'
    slug_url_kwarg = 'slug_param'
    success_url = reverse_lazy('administrator:start')

magazin/user/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from app.models import Magazin


class StartPage(TemplateView):
    template_name = 'users/start.html'


class ProductList(ListView):
    model = Magazin
    template_name = 'users/product_list.html'
    context_object_name = 'products'


class ProductDetail(DetailView):
    template_name = 'users/detail.html'
    model = Magazin
    slug_field = 'slug'
    slug_url_kwarg = 'slug_param'

magazin/app/templates/app/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h1>Add Product</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
  </form>
  <p><a href="{% url 'administrator:start' %}">Back</a></p>
</body>
</html>

magazin/app/templates/app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Start</h1>
<p><a href="{% url 'administrator:add' %}">Add</a></p>
<p><a href="{% url 'administrator:products' %}">Products</a></p>

</body>
</html>

magazin/app/templates/app/products.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Products</title>
</head>
<body>
<h1>Products</h1>
    {% for product in products %}
    <p>{{ product }}</p>
    <p><a href="{% url 'administrator:update' product.slug %}">Update</a></p>
    {% endfor %}
    <p><a href="{% url 'administrator:start' %}">Back</a></p>

</body>
</html>

magazin/app/templates/app/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update</title>
</head>
<body>
<h1>Update</h1>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Update">
</form>
<p><a href="{% url 'administrator:products' %}">Back</a></p>
</body>
</html>

magazin/user/templates/users/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>
<h1>Detail</h1>

    <p>{{ product.title }}</p>
    <p>{{ product.category }}</p>
    <p>{{ product.price }}</p>
    <p>{{ product.status }}</p>
    <p>{{ product.date_of_purchase }}</p>

</body>
</html>

magazin/user/templates/users/product_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Product</title>
</head>
<body>
<h1>Product List</h1>
    {% for product in products %}
    <p>{{ product }}</p>
    <p><a href="{% url 'users:detail' product.slug %}">Detail</a></p>
    {% endfor %}
    <p><a href="{% url 'users:start' %}">Back</a></p>

</body>
</html>

magazin/user/templates/users/start.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Start</title>
</head>
<body>
<h1>Start</h1>
<p><a href="{% url 'users:products' %}">Products</a></p>
</body>
</html>